[libraries]

osvvm.files = [
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/AlertLogPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/CoveragePkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/MemoryGenericPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/MemoryPkg.vhd',
    #'.venv/Lib/site-packages/vunit/vhdl/osvvm/MemoryPkg_c.vhd',
    #'.venv/Lib/site-packages/vunit/vhdl/osvvm/MemoryPkg_orig_c.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/MemorySupportPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/MessageListPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/MessagePkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/NamePkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/NameStorePkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/OsvvmContext.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/OsvvmScriptSettingsPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/OsvvmScriptSettingsPkg_default.vhd',
    #'.venv/Lib/site-packages/vunit/vhdl/osvvm/OsvvmSettingsPkg.vhd',
    #'.venv/Lib/site-packages/vunit/vhdl/osvvm/OsvvmSettingsPkg_default.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/OsvvmGlobalPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/OsvvmTypesPkg.vhd',
    #'.venv/Lib/site-packages/vunit/vhdl/osvvm/DelayCoveragePkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/RandomBasePkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/RandomPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/RandomProcedurePkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/ReportPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/ResizePkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/ResolutionPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/ScoreboardGenericPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_int.vhd',
    #'.venv/Lib/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_int_c.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_slv.vhd',
    #'.venv/Lib/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_slv_c.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/SortListPkg_int.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/TbUtilPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/TextUtilPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/TranscriptPkg.vhd',
    '.venv/Lib/site-packages/vunit/vhdl/osvvm/VendorCovApiPkg.vhd',
    #'.venv/Lib/site-packages/vunit/vhdl/osvvm/VendorCovApiPkg_Aldec.vhd',
]
osvvm.is_third_party = true

vunit_lib.files = [
    ".venv/Lib/site-packages/vunit/vhdl/check/src/check_api.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/check/src/check.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/check/src/checker_pkg-body.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/check/src/checker_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/com/src/com_api.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/com/src/com_common.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/com/src/com_context.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/com/src/com_debug_codec_builder.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/com/src/com_deprecated.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/com/src/com_messenger.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/com/src/com_string.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/com/src/com_support.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/com/src/com_types.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/com/src/com.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/core/src/core_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/core/src/stop_body_2008p.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/core/src/stop_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/api/external_string_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/codec_builder-2008p.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/codec_builder.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/codec-2008p.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/codec.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/data_types_context.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/data_types_private_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/dict_pkg-2008p.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/dict_pkg-body.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/dict_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/id_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/integer_array_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg-body-2002p.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/queue_pkg-body.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/queue_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/queue_pool_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/types.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/event_common_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/event_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/src/event_private_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/test/tb_event_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/data_types/test/tb_event_private_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/dictionary/src/dictionary.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/common_log_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/common_log_pkg-body.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/ansi_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/file_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/location_pkg-body-2008m.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/location_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/log_handler_pkg-body.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/log_handler_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/log_levels_pkg-body.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/log_levels_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/logger_pkg-body.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/logger_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/print_pkg-body.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/logging/src/print_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/path/src/path.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/run/src/run_api.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/run/src/run_types.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/run/src/run.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/run/src/runner_pkg.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/string_ops/src/string_ops.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/vunit_context.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/vunit_run_context.vhd",
    ".venv/Lib/site-packages/vunit/vhdl/random/src/random_pkg.vhd"]
vunit_lib.is_third_party = true


mylib.files = ['source/**/*.vhd','testbench/**/*.vhd', 'vivado/**/*.vhd']
mylib.is_third_party = false